### ISSUE TITLE
instructions overlay should be transparent

### ISSUE THREAD

**Issue by lengstrom** [Hextris/hextris#116]

**Comment by merodriguezblanco** [comment]
I checked the game on my iPad (Safari, iOS 8.1.3) and I see that when you tap on the instructions, the information is being displayed on a box with a specific opacity.

Do you want to remove that opacity only for iPad or for all browsers and devices?

**Comment by meadowstream** [comment]
@garrettdreyfus @merodriguezblanco I think it's fine as it is right now. We're in the middle of releasing a new version of Hextris - we'll probably change up how instructions are done in the next version, anyway. Thanks anyway, though! :beers:
