### ISSUE TITLE
Great game - Added to Firefox Marketplace

### ISSUE THREAD

**Issue by yiannakis** [Hextris/hextris#117]
Hello and congratulations for the wonderful job you did for this great and addicting game.
I am a Mozilla enthusiast and also a participator in Tablet Contribution Program -for FirefoxOS, and i submitted the game to Firefox Marketplace for everyone to see and play.

I added all the links for Github and your names on game description and hope you don't have any problem.

Thank you very much again for this great game. :+1: 

Here is the link : https://marketplace.firefox.com/app/hextris-app

**Comment by lengstrom** [comment]
Any updates?
