### ISSUE TITLE
Allow "d" to be used with the same functionality as "down"

### ISSUE THREAD

**Issue by williamg** [Hextris/hextris#127]
Since "w" and "a" already work for "left" and "right", it makes sense to let "d" work as "down"

**Comment by imsarath** [comment]
Currently "a" and "d" work for left and right. It makes sense if we mark "s" for "down". That's, I suppose, are the usual game controls.

**Comment by green-big-frog** [comment]
"w" up
"a" left
"s" down
"d" right

+1

**Comment by samjray9** [comment]
"D should be right" 
"S" should be down

That's what i thought it was

**Comment by imsarath** [comment]
I think the only controls here are clock-wise and anti-clock wise. I think it makes sense to have D for right and A for left.

**Comment by themichaelyang** [comment]
🤔❓

**Comment by themichaelyang** [comment]
Fixed, down + S now speed up block speed.
