### ISSUE TITLE
Clarify GPL version.

### ISSUE THREAD

**Issue by Jookia** [Hextris/hextris#151]
Despite saying the project is under GPLv3, the source code doesn't note this or note if it's able to be upgraded to a future GPL version or not.

**Comment by themichaelyang** [comment]
Hi, cleaning up some of these long lost issues. Could you elaborate on this problem?

**Comment by Jookia** [comment]
The source code files ( https://github.com/Hextris/hextris/blob/gh-pages/js/view.js ) and the README aren't clear about what specific license the code is under. Usually they would say 'GPLv3 or later' or 'GPLv3 only' but the source code has no license header and the README just says 'This work is under a GPL v3 license.'

**Comment by themichaelyang** [comment]
I see; I've updated the README with the appropriate preamble. Is that sufficient?

**Comment by Jookia** [comment]
Perfect!
