### ISSUE TITLE
Introductory text grows massive in mobile

### ISSUE THREAD

**Issue by lengstrom** [Hextris/hextris#152]
should fix

@garrettdreyfus thoughts on why this happens?

**Comment by garrettdreyfus** [comment]
I made it 24 px but didn't notice it on my phone when I tested it or on
other screens in the dev console.

**Comment by lengstrom** [comment]
hm yeah idk why its happening on my emulator ill investigate

**Comment by lengstrom** [comment]
so this bug doesnt happen on ur devices?

**Comment by garrettdreyfus** [comment]
Oh you should open a new incognito tab put it in emulator and then go to
your test server or else it doesn't work
