### ISSUE TITLE
[Ubuntu Touch OTA9.1] [Aquaris E5] Font text is too big

### ISSUE THREAD

**Issue by cibersheep** [Hextris/hextris#164]
At the screen where score is shown, and it's been asked to press to start again, font text is too big (and sentence is shown twice one on top of the other)

**Comment by lengstrom** [comment]
Hi @cibersheep - thanks for making an issue! Can you give more concrete instructions on how to replicate this?

**Comment by cibersheep** [comment]
I did a screen capture. It shows like this every time that I finish a game.
If you need more info, please let me know.

![photo_2016-03-10_21-09-38](https://cloud.githubusercontent.com/assets/6640041/13683028/d57e1a14-e704-11e5-8d84-724a005b818d.jpg)

**Comment by lengstrom** [comment]
Can you try in http://hextris.io/? does it work there?

**Comment by cibersheep** [comment]
Yep.
Looks good... I attach screenshots.



El dimecres, 23 març de 2016 4.20.14 CET, el/la Logan Engstrom 
<notifications@github.com> va escriure:
> Can you try in http://hextris.io/? does it work there?
> 
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/Hextris/hextris/issues/164#issuecomment-200148568


-- 
Enviat amb el Dekko des del meu telèfon Ubuntu

**Comment by cibersheep** [comment]
![screenshot20160323_100722234](https://cloud.githubusercontent.com/assets/6640041/14001935/ef6f58ea-f148-11e5-923e-6a51553214c0.png)
![screenshot20160323_100520044](https://cloud.githubusercontent.com/assets/6640041/14001936/ef99af0a-f148-11e5-916d-6d0300f7e14b.png)

**Comment by lengstrom** [comment]
Thanks!
