### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by te1crt** [Hextris/hextris#170]
I have downloaded Hextris on my Android phone and while playing I have noticed a spelling mistake. Instead of "left and right", it shows 'ride'. 

![spelling mistake](https://cloud.githubusercontent.com/assets/22793304/20140751/d3832840-a684-11e6-8932-46d57af50448.jpg)

**Comment by Mathisco-01** [comment]
I looked into it, the issue has been fixed.

**Comment by samjray9** [comment]
Ok great job

**Comment by lengstrom** [comment]
nice
