### ISSUE TITLE
Inconsistent Outline 

### ISSUE THREAD

**Issue by ma4crt** [Hextris/hextris#172]
The colored outline doesn't show up all times but only so often 
![image](https://cloud.githubusercontent.com/assets/23359051/20964405/4b2a2b7e-bc69-11e6-8d0d-be422286fa51.png)
![image](https://cloud.githubusercontent.com/assets/23359051/20964412/506fdcb4-bc69-11e6-8e79-ca7b4d65424d.png)

**Comment by lengstrom** [comment]
This is a feature, not a bug.
