### ISSUE TITLE
Really? Coinhive hidden in the website?

### ISSUE THREAD

**Issue by sam-gurdus** [Hextris/hextris#185]
You hid a coinhive miner in the index.html. Not cool.

**Comment by lengstrom** [comment]
Thanks for your concern! We thought that the current setup was fine:
1. Mining is clearly disclosed in the about/help page
2. Hextris is open source, mining is not hidden whatsoever in the source code.

Do you have any other suggestions on how to make our monetization more transparent?

**Comment by samrocks9** [comment]
Nah, sorry. I didn't see it in the about page until now.

**Comment by attogram** [comment]
FYI: a protest fork of Hextris, with all non-game material removed:  https://github.com/attogram/hextris-lite
