### ISSUE TITLE
Norton detected suspicious activity -- JSCoinMiner?

### ISSUE THREAD

**Issue by adnanusman** [Hextris/hextris#190]
I was going to use this in a project for my Google Scholarship project (we were going to add a service worker to it) but when we started exploring your application. A colleague of mine @franciscojgtz ended up getting alerts on Norton Antivirus:

![jscoinminer](https://user-images.githubusercontent.com/28072874/37939572-633dc516-3118-11e8-8e06-61e54a16d5ac.png)

We suspect his code in index.html may be the issue? Why is this in there anyway?  (never mind.. I saw the disclaimer in the about section in the Readme.. however please note this is setting off antiviruses and really isn't ideal).

**Comment by franciscojgtz** [comment]
I also found this information about JSCoinminer: https://www.symantec.com/security_response/attacksignatures/detail.jsp?asid=30303

**Comment by adnanusman** [comment]
The virus warning goes away when we remove that commented out code. I guess this can be marked as closed as we understand why that code is there now. Very nice work on this game! :)
