### ISSUE TITLE
Hextris Lite - a protest fork

### ISSUE THREAD

**Issue by attogram** [Hextris/hextris#205]
Please be advised concerning a new fork of the Hextris codebase.  

It was created in protest against the continued presence of `Trojan:JS/CoinHive.B` in the Hextris repository.

It is called **Hextris Lite**.   All non-game scripts and material have been removed, leaving just a playable game.   Please see the README for more information:

https://github.com/attogram/hextris-lite

[![Hextris Lite](https://raw.githubusercontent.com/attogram/attogram-docs/master/hextris-lite/hextris-lite.png)](https://github.com/attogram/hextris-lite)

**Comment by themichaelyang** [comment]
The `gh-pages` (our main branch) does not have any Coinhive monetization; this was resolved a long time ago! We have Coinhive on hextris.io in order to fund our domain name, but seeing as many corporate firewalls don't like it, we might remove it. Coinhive is really not dangerous and not much different from ad-based monetization. So no reason to protest :-)

**Comment by attogram** [comment]
I do not agree on your stance about the Coinhive trojan.

As for the gh-pages branch, it is heavily branded for your own deployment, including analytics tracking codes.   That is fine for your usage.   But it is a no-go for others to use.   

Might you consider creating a new clean branch with no branding and tracking?

**Comment by themichaelyang** [comment]
It seems like you've already done that, which is cool! I'm sad to hear you call Hextris "profoundly troubling", so I wanted to clarify that the script was not in fact a trojan. This was already handled in a previous issue and it was removed from source. Either way, it looks like Coinhive has shut down, so we're going to remove it from our hosted version as well. 

Glad we can finally put this issue to rest, hope you enjoy the update! 🤙

**Comment by attogram** [comment]
The call to the trojan is still in the repo, and still triggers many vulnerability scanners.   Commenting it out isn't enough.   Tracking analytics codes are still in the repo, causing potential liability issues for anyone who deploys it.   

These issue can be overcome eventually.   We agree that Hextris is a cool game.
