### ISSUE TITLE
Not available on Australian App Store

### ISSUE THREAD

**Issue by rbits0** [Hextris/hextris#209]
I have an Australian iTunes account, and when I tap on Download in the App Store it says “This app is currently not available in your country or region”. Would you be able to put it on the Australian App Store, or even just release an ipa so I can sideload it onto my phone if putting it on the Australian app store is too hard?

**Comment by lengstrom** [comment]
there are no releasees of hextris on the app store right now (other than probably illegally distributed versions), you are best off just visiting hextris.io!
